# Generated by Django 3.0.4 on 2020-03-27 10:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identification_card_picture_front', models.ImageField(blank=True, null=True, upload_to='userIdentificationCard', verbose_name='Identification Card Front')),
                ('user_identification_card_picture_back', models.ImageField(blank=True, null=True, upload_to='userIdentificationCard', verbose_name='Identification Card Back')),
                ('user_identification_card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Identification Card Number')),
                ('user_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user_profile_picture', models.ImageField(blank=True, null=True, upload_to='profilePicture', verbose_name='User Passport Size Photo')),
                ('user_phone_number', models.CharField(help_text='Only Nepalese number available for now, Format: 98XXXXXXXX', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
