# Generated by Django 3.0.4 on 2020-03-27 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_identification_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Identification Card Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_phone_number',
            field=models.CharField(help_text='Only Nepalese number available for now, Format: 98XXXXXXXX', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number'),
        ),
    ]
