# Generated by Django 3.0.4 on 2020-03-30 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200330_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=512, verbose_name='Address')),
                ('user_city', models.CharField(max_length=256, verbose_name='city')),
                ('user_country', models.CharField(max_length=128, verbose_name='country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
